// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebApIFaod2025.Helpers;

#nullable disable

namespace WebApIFaod2025.Migrations
{
    [DbContext(typeof(bdTracking01Context))]
    [Migration("20251031213248_SecurityAddOns3")]
    partial class SecurityAddOns3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebApIFaod2025.Entities.Colis", b =>
                {
                    b.Property<int>("IdColis")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdColis"));

                    b.Property<int?>("ClientId")
                        .HasColumnType("integer");

                    b.Property<string>("CodeColis")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("DescriptionColis")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("LibelleColis")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int?>("LivreurId")
                        .HasColumnType("integer");

                    b.Property<float>("PoidsColis")
                        .HasColumnType("real");

                    b.Property<string>("TypeColis")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("IdColis");

                    b.HasIndex("ClientId");

                    b.HasIndex("LivreurId");

                    b.ToTable("Colis");
                });

            modelBuilder.Entity("WebApIFaod2025.Entities.DemandeColis", b =>
                {
                    b.Property<int>("IdDemande")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDemande"));

                    b.Property<string>("AdresseEnlevement")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("AdresseLivraison")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateDemande")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("PoidsEstime")
                        .HasColumnType("real");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TypeColis")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("IdDemande");

                    b.HasIndex("ClientId");

                    b.ToTable("DemandeColis");
                });

            modelBuilder.Entity("WebApIFaod2025.Entities.SuiviCommande", b =>
                {
                    b.Property<int>("IdSuivi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdSuivi"));

                    b.Property<int>("ColisId")
                        .HasColumnType("integer");

                    b.Property<string>("Commentaire")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("DateMiseAJour")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PositionGPS")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("IdSuivi");

                    b.HasIndex("ColisId");

                    b.ToTable("SuiviCommande");
                });

            modelBuilder.Entity("WebApIFaod2025.Entities.UsersColis", b =>
                {
                    b.Property<int>("IdUsersColis")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUsersColis"));

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("CNI")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.HasKey("IdUsersColis");

                    b.ToTable("UsersColis");

                    b.HasDiscriminator().HasValue("UsersColis");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("WebApIFaod2025.Entities.Client", b =>
                {
                    b.HasBaseType("WebApIFaod2025.Entities.UsersColis");

                    b.Property<string>("CodeClient")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.HasDiscriminator().HasValue("Client");
                });

            modelBuilder.Entity("WebApIFaod2025.Entities.Livreur", b =>
                {
                    b.HasBaseType("WebApIFaod2025.Entities.UsersColis");

                    b.Property<string>("CarteGris")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Matricule")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Premis")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.HasDiscriminator().HasValue("Livreur");
                });

            modelBuilder.Entity("WebApIFaod2025.Entities.Colis", b =>
                {
                    b.HasOne("WebApIFaod2025.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId");

                    b.HasOne("WebApIFaod2025.Entities.Livreur", "Livreur")
                        .WithMany()
                        .HasForeignKey("LivreurId");

                    b.Navigation("Client");

                    b.Navigation("Livreur");
                });

            modelBuilder.Entity("WebApIFaod2025.Entities.DemandeColis", b =>
                {
                    b.HasOne("WebApIFaod2025.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("WebApIFaod2025.Entities.SuiviCommande", b =>
                {
                    b.HasOne("WebApIFaod2025.Entities.Colis", "Colis")
                        .WithMany("SuiviCommande")
                        .HasForeignKey("ColisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Colis");
                });

            modelBuilder.Entity("WebApIFaod2025.Entities.Colis", b =>
                {
                    b.Navigation("SuiviCommande");
                });
#pragma warning restore 612, 618
        }
    }
}
